name: emip
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2019.11.28
  - certifi=2019.11.28
  - cftime=1.0.4.2
  - curl=7.68.0
  - cycler=0.10.0
  - expat=2.2.9
  - freetype=2.10.0
  - gsl=2.6
  - hdf4=4.2.13
  - hdf5=1.10.5
  - icc_rt=2019.0.0
  - icu=64.2
  - intel-openmp=2019.5
  - jpeg=9c
  - kiwisolver=1.1.0
  - krb5=1.16.4
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.1
  - libcurl=7.68.0
  - liblapack=3.8.0
  - libnetcdf=4.7.3
  - libpng=1.6.37
  - libssh2=1.8.2
  - matplotlib=3.1.2
  - matplotlib-base=3.1.2
  - mkl=2019.5
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.0
  - nco=4.9.2
  - netcdf4=1.5.3
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openssl=1.1.1d
  - pandas=0.25.3
  - pip=20.0.2
  - pyparsing=2.4.6
  - pyqt=5.12.3
  - python=3.6.7
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pytz=2019.3
  - qt=5.12.5
  - scipy=1.3.2
  - setuptools=45.2.0
  - six=1.14.0
  - sqlite=3.30.1
  - tk=8.6.10
  - tornado=6.0.3
  - udunits2=2.2.27.6
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wheel=0.34.2
  - wincertstore=0.2
  - zlib=1.2.11
  - pip:
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1

