###############################################################################
# User's configuration file for the ESMValTool
#
# A simple first config file to get aquainted with ESMValTool and CAM5 output
# as part of the Emissions-MIP
#
# Matt Nicholson
# Pacific Northwest National Laboratory - Joint Global Change Research Institute
# 5 Feb 2020
###############################################################################
---

# Rootpaths to the data from different projects
rootpath:
  CMIP5: ~/esmvaltool/input
  default: ~/esmvaltool/input

# Directory structure for input data: [default]/BADC/DKRZ/ETHZ/etc
# See config-developer.yml for definitions.
#
# Since the CMIP5 root path structure (below) is set to 'default',
# the input data MUST by located in the same top-level directory set by
# rootpath:default
# See: 
# (https://esmvaltool.readthedocs.io/projects/esmvalcore/en/latest/esmvalcore/
#  datafinder.html#explaining-config-user-drs-cmip5-or-config-user-drs-cmip6)
drs:
  CMIP5: default
 
# Run at most this many tasks in parallel null/[1]/2/3/4/..
# Set to null to use the number of available CPUs.
# Make sure your system has enough memory for the specified number of tasks.
max_parallel_tasks: 1

# Destination directory
output_dir: ~/esmvaltool/output

# Auxiliary data directory (used for some additional datasets)
auxiliary_data_dir: ~/esmvaltool/auxiliary_data

# Diagnostics create plots? [true]/false
write_plots: true

# Diagnositcs write NetCDF files? [true]/false
write_netcdf: true

# Set the console log level debug, [info], warning, error
log_level: info

# Exit on warning? true/[false]
exit_on_warning: false

# Plot file format? [ps]/pdf/png/eps/epsi
output_file_type: pdf

# Use netCDF compression true/[false]
compress_netcdf: false

# Save intermediary cubes in the preprocessor true/[false]
save_intermediary_cubes: false

# Remove the preproc dir if all fine
remove_preproc_dir: true

# Path to custom config-developer file, to customise project configurations.
# See config-developer.yml for an example. Set to None to use the default
# config_developer_file: null
# Get profiling information for diagnostics
# Only available for Python diagnostics
profile_diagnostic: false